Update Readme.md
MadhushaPrasad/Diagon-Alley pull request #31
Opened 2022-10-17 17:09 UTC by acenasir

Figma Link Added

2022-10-17 23:15 UTC, MadhushaPrasad commented
cam you please add some valuable text above thr figma link.And also export the Home page and attached it to the readme file

2022-10-18 02:10 UTC, MadhushaPrasad commented
@IndudiniThennakoon

2022-10-18 02:12 UTC, MadhushaPrasad requested changes

2022-10-18 02:12 UTC, MadhushaPrasad commented on README.md
> +<a href="[https://www.w3.org/html/](https://www.figma.com/file/dz4JS3XBiGzTDGGIQ3PczB/Diagon-Alley?node-id=20%3A782)" target="_blank"> Figma Designs </a.
The link is not working

2022-10-18 10:40 UTC, IndudiniThennakoon requested changes

2022-10-18 10:40 UTC, IndudiniThennakoon commented on README.md
> +<a href="[https://www.w3.org/html/](https://www.figma.com/file/dz4JS3XBiGzTDGGIQ3PczB/Diagon-Alley?node-id=20%3A782)" target="_blank"> Figma Designs </a.
@acenasir link is not working. please update it correctly

2022-10-18 15:33 UTC, closed without merging