update contactus.php
MadhushaPrasad/Diagon-Alley pull request #67
Opened 2023-10-03 16:54 UTC by nethu99

2023-10-03 16:59 UTC, MadhushaPrasad commented
Please drop the screenshot here that you are implemented

2023-10-03 17:13 UTC, MadhushaPrasad requested changes
We need to implement extract UI, just like the Figma file.

2023-10-06 06:34 UTC, supuna97 commented
Try to write CSS in another class. Don't write inline CSS. Its not good for the SEO. @nethu99

2023-10-06 06:35 UTC, supuna97 requested changes

2023-10-06 06:35 UTC, supuna97 commented on components/contactus.php
> +                        <textarea name="txtemsg" class="form-control" placeholder="message" style="width: 100%; height: 100px;"></textarea>
Try to write CSS in another class. Don't write inline CSS. Its not good for the SEO. @nethu99

2023-10-14 02:24 UTC, closed without merging